# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 665b4a106a415ffc420c4da9998291ecb33e58a7cff22ffac960c349b0a994631a1fcb4b710bf7941577962d0726909623ff65d82f20c6ed103e8e3b7fd2b17c

test:
  secret_key_base: 462e2699e9b6c8c55b882f0832e893502a7f873dc654e1fcc62bb0f1b021492f7bfa49e360907cb1a5c78e0f98cd69a5d08db5fdda7fa550aef242c71ea3f9e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
